version: '2.4'

services:
  keycloak:
    image: jboss/keycloak:9.0.3
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      - KEYCLOAK_LOGLEVEL=INFO
      - DB_VENDOR=H2
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - want-client-auth=true
      - WANT-CLIENT-AUTH=true
      - X509_CA_BUNDLE=/etc/x509/ca/ca.crt
      - KEYCLOAK_IMPORT=/conf/import/cac-test-realm-realm.json
    volumes:
      - ./certs/tls.crt:/etc/x509/https/tls.crt
      - ./certs/tls.key:/etc/x509/https/tls.key
      - ./certs/ca.crt:/etc/x509/ca/ca.crt
      - ./realms:/conf/import
